version: '3'

services:

  db:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_db
    volumes:
      - ./source/db_data:/var/lib/mysql
      - ./source/db_import:/data_import
      - ./tools/import.sh:/data_import/import.sh
    ports:
      - "13308:3306"
    restart: always
    env_file:
      - settings.env

  web:
    container_name: ${PROJECT_NAME}_web
    build: ./docker-web
    volumes:
      - ./source/web:/var/www/html
      - ./tools/fix-perms.sh:/fix-perms.sh
    ports:
      - "8082:80"
    depends_on:
      - db
    links:
      - db
    restart: always
    env_file: settings.env
    environment:
      MYSQL_HOST: db
